# Generated by Django 2.2.12 on 2021-10-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='img',
        ),
    ]
