# Generated by Django 2.2.12 on 2021-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='all_comments',
            field=models.ManyToManyField(to='auctions.Comment'),
        ),
    ]
