# Generated by Django 2.2.12 on 2021-11-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211102_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishitem',
        ),
    ]
